name = "UrlDownload"
uuid = "856ac37a-3032-4c1c-9122-f86d88358c8b"
authors = ["Andrey Oskin"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
